import Head from 'next/head';
import Image from 'next/image';
import heroImg from '../public/images/hero.svg';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Client Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon/logo_size.jpg" />
      </Head>

      <section className="flex flex-col items-center justify-center h-[calc(100vh-64px)]">
        <h2 className="text-6xl text-purple-800 font-bold mb-20">Client Portal</h2>
        <Image
          src={heroImg}
          width={400}
          height={400}
        className="block" />
        <Link href="/login" className="block">
          <a className="px-4 py-2 bg-purple-800 text-white mt-8 hover:scale-110 transition ease-linear duration-300">Login / Register</a>
        </Link>
      </section>
    </div>
  );
}
