import Head from 'next/head';
import Image from 'next/image';
import heroImg from '../public/images/hero.svg';

export default function Home() {
  return (
    <div className='flex items-center justify-center h-screen'>
      <Head>
        <title>Client Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon/logo_size.jpg" />
      </Head>

      <section className="flex border-2 justify-center">
        <Image src={heroImg} width={400} height={400}></Image>
      </section>
     
    </div>
  )
}
